site_name: My Docs
site_url: https://example.com/

theme:
        logo: material/assets/right.ico
        name: material

markdown_extensions:
        - admonition
        - pymdownx.superfences 
        - pymdownx.highlight:
                linenums: true
        